"""
skills.py — Bilingual (EN + TR) beceri sözlüğü. Gerçek mühendis yelpazesini
kapsayacak şekilde kategori kategori düzenlenmiştir.

YAPI:
    SKILL_CATEGORIES: dict[str, dict[str, list[str]]]
        "Kategori Adı 🙂" -> { canonical_name -> [varyant1, varyant2, ...] }

    SKILLS: dict[str, list[str]]   (SKILL_CATEGORIES'ten DÜZLEŞTİRİLİR)
        canonical_name -> [varyant1, ...]   — extractor & raporlar bunu kullanır.

    canonical_name : trend grafiklerinde/raporlarda görünecek tek isim (genelde EN).
    varyantlar     : ilan metninde aranacak tüm yazımlar (EN + TR + kısaltma).

KURALLAR:
    - Tüm varyantlar küçük harf. Eşleştirme küçük harfe normalize edilmiş metinde yapılır.
    - Kısa/ikircikli kısaltmalar (ör. "r", "go", "s3", "iam", "rl") kelime-sınırı
      (\\b...\\b) ile aranmalı; bu liste processors/skill_extractor.py içindeki
      _WORD_BOUNDARY_VARIANTS'ta tutulur. Yeni riskli kısaltma eklersen ORAYA da ekle.
    - Sahte pozitif riski yüksek YALIN kelimeler (chef→aşçı, glue, echo, gin, beam...)
      ürün-adı niteleyiciyle aranır (ör. "aws glue", "gin framework") ya da yalın hâli
      bilinçli olarak dışarıda bırakılır.
    - Bir canonical SADECE BİR kategoride bulunur (düzleştirme yinelenenleri reddeder).
"""

SKILL_CATEGORIES: dict[str, dict[str, list[str]]] = {
    # =====================================================================
    "Programlama Dilleri 💻": {
        "python": ["python"],
        "javascript": ["javascript", "js"],
        "typescript": ["typescript", "ts"],
        "java": ["java"],
        "c#": ["c#", "c sharp", "csharp", ".net", "dotnet"],
        "c++": ["c++", "cpp", "c plus plus"],
        "c": ["c programlama", "c language"],  # yalın "c" FP riski yüksek
        "go": ["golang", "go lang"],
        "rust": ["rust"],
        "php": ["php"],
        "ruby": ["ruby", "ruby on rails", "rails"],
        "swift": ["swift"],
        "kotlin": ["kotlin"],
        "scala": ["scala"],
        "r": ["r programlama", "r language"],  # yalın "r" yerine niteleyici
        "matlab": ["matlab"],
        "julia": ["julia programlama", "julia language", "julia lang"],  # isim FP'si
        "bash": ["bash"],
        "shell": ["shell script", "shell scripting", "kabuk betiği", "kabuk betigi"],
        "objective-c": ["objective-c", "objective c", "objc"],
        "perl": ["perl"],
        "haskell": ["haskell"],
        "elixir": ["elixir"],
        "clojure": ["clojure"],
    },
    # =====================================================================
    "AWS Servisleri ☁️": {
        "ec2": ["ec2", "amazon ec2"],
        "s3": ["s3", "amazon s3"],
        "lambda": ["aws lambda", "lambda function"],  # yalın "lambda" Python ile karışır
        "ecs": ["ecs", "elastic container service"],
        "eks": ["eks", "elastic kubernetes service"],
        "rds": ["rds", "amazon rds"],
        "dynamodb": ["dynamodb", "dynamo db"],
        "sagemaker": ["sagemaker", "sage maker"],
        "bedrock": ["aws bedrock", "amazon bedrock"],  # yalın "bedrock" jenerik kelime
        "cloudwatch": ["cloudwatch", "cloud watch"],
        "vpc": ["vpc"],
        "aurora": ["aurora", "amazon aurora"],
        "redshift": ["redshift", "red shift"],
        "teradata": ["teradata"],
        "api gateway": ["api gateway", "api gateway pattern"],
        "step functions": ["step functions", "aws step functions"],
        "glue": ["aws glue"],  # yalın "glue" jenerik kelime
        "athena": ["athena", "amazon athena", "aws athena"],
        "emr": ["emr", "elastic mapreduce"],
    },
    # =====================================================================
    "Azure Servisleri ☁️": {
        "azure functions": ["azure functions"],
        "aks": ["aks", "azure kubernetes service"],
        "cosmos db": ["cosmos db", "cosmosdb", "azure cosmos"],
        "blob storage": ["blob storage", "azure blob"],
        "azure ml": ["azure ml", "azure machine learning"],
        "azure devops": ["azure devops", "azure pipelines"],
        "synapse analytics": ["synapse analytics", "azure synapse", "synapse"],
        "azure data factory": ["azure data factory"],
        "azure openai": ["azure openai", "azure open ai"],
    },
    # =====================================================================
    "GCP Servisleri ☁️": {
        "bigquery": ["bigquery", "big query"],
        "vertex ai": ["vertex ai", "vertexai"],
        "cloud run": ["cloud run"],
        "gke": ["gke", "google kubernetes engine"],
        "pub/sub": ["pub/sub", "pubsub", "pub sub"],
        "cloud functions": ["cloud functions"],
        "dataflow": ["dataflow", "cloud dataflow"],  # yalın "data flow" jenerik
        "firebase": ["firebase"],
        "cloud storage": ["cloud storage", "google cloud storage", "gcs"],
    },
    # =====================================================================
    "Veritabanları 🗄️": {
        "sql": ["sql"],
        "postgresql": ["postgresql", "postgres"],
        "mysql": ["mysql"],
        "mongodb": ["mongodb", "mongo db", "mongo"],
        "oracle": ["oracle db", "oracle database"],
        "sql server": ["sql server", "mssql", "microsoft sql server"],
        "cassandra": ["cassandra", "apache cassandra"],
        "nosql": ["nosql", "no sql"],
        "redis": ["redis"],
        "elasticsearch": ["elasticsearch", "elastic search"],
        "opensearch": ["opensearch", "open search"],
        "neo4j": ["neo4j", "neo 4j"],
        "influxdb": ["influxdb", "influx db"],
        "clickhouse": ["clickhouse", "click house"],
        "pinecone": ["pinecone", "pine cone"],
        "weaviate": ["weaviate"],
        "chroma": ["chromadb", "chroma db"],  # yalın "chroma" (chrome/chromatic) FP
        "pgvector": ["pgvector", "pg vector"],
    },
    # =====================================================================
    "Veri Mühendisliği 🔧": {
        "apache flink": ["apache flink", "flink"],
        "apache beam": ["apache beam"],  # yalın "beam" jenerik
        "apache hive": ["apache hive"],  # yalın "hive" → "archive" FP
        "hdfs": ["hdfs"],
        "prefect": ["prefect"],
        "dagster": ["dagster"],
        "luigi": ["luigi"],
        "great expectations": ["great expectations"],
        "dbt": ["dbt", "data build tool"],
        "fivetran": ["fivetran", "five tran"],
        "stitch": ["stitch data", "stitch etl"],  # yalın "stitch" jenerik
        "airbyte": ["airbyte", "air byte"],
        "nifi": ["nifi", "apache nifi"],
        "airflow": ["airflow", "apache airflow"],
        "kafka": ["kafka", "apache kafka"],
        "spark": ["spark", "apache spark", "pyspark"],
        "hadoop": ["hadoop"],
        "snowflake": ["snowflake"],
        "databricks": ["databricks"],
        "etl": ["etl", "veri ardışığı", "data pipeline"],
    },
    # =====================================================================
    "ML / AI 🤖": {
        "machine learning": ["machine learning", "makine öğrenmesi", "makine ogrenmesi", "ml"],
        "deep learning": ["deep learning", "derin öğrenme", "derin ogrenme"],
        "reinforcement learning": ["reinforcement learning", "pekiştirmeli öğrenme",
                                   "pekistirmeli ogrenme", "rl"],
        "data science": ["data science", "veri bilimi", "veri bilimci"],
        "data analysis": ["data analysis", "veri analizi", "data analyst", "veri analisti"],
        "nlp": ["nlp", "natural language processing", "doğal dil işleme", "dogal dil isleme"],
        "computer vision": ["computer vision", "bilgisayarlı görü", "bilgisayarli goru"],
        "pandas": ["pandas"],
        "numpy": ["numpy"],
        "tensorflow": ["tensorflow", "tensor flow"],
        "pytorch": ["pytorch", "py torch"],
        "scikit-learn": ["scikit-learn", "scikit learn", "sklearn"],
        "keras": ["keras"],
        "xgboost": ["xgboost", "xg boost"],
        "lightgbm": ["lightgbm", "light gbm"],
        "catboost": ["catboost", "cat boost"],
        "transformers": ["transformers", "transformer model"],
        "bert": ["bert"],
        "gpt": ["gpt", "chatgpt", "gpt-4", "gpt-3", "gpt-4o"],
        "stable diffusion": ["stable diffusion"],
        "hugging face": ["hugging face", "huggingface"],
        "langchain": ["langchain", "lang chain"],
        "openai api": ["openai api", "openai", "open ai"],
        "llm": ["llm", "large language model", "büyük dil modeli", "buyuk dil modeli"],
        "rag": ["rag", "retrieval augmented generation", "retrieval-augmented generation"],
        "embedding": ["embedding", "embeddings", "gömme vektör", "gomme vektor"],
        "vector database": ["vector database", "vektör veritabanı", "vektor veritabani",
                            "vector db"],
        "feature store": ["feature store"],
        "weights and biases": ["weights and biases", "weights & biases", "wandb"],
        "mlflow": ["mlflow", "ml flow"],
        "kubeflow": ["kubeflow", "kube flow"],
        "bentoml": ["bentoml", "bento ml"],
        "triton inference server": ["triton inference server", "triton"],
        "onnx": ["onnx"],
        "prompt engineering": ["prompt engineering", "prompt tasarımı", "prompt tasarimi",
                               "few shot prompting", "chain of thought"],
        "llm fine tuning": ["llm fine tuning", "fine tuning", "finetuning",
                            "lora", "qlora", "peft", "instruction tuning"],
        "semantic search": ["semantic search", "anlamsal arama",
                            "dense retrieval", "bi-encoder"],
        "image generation": ["image generation", "görüntü üretimi", "goruntu uretimi",
                             "text to image", "diffusion models"],
        "speech recognition": ["speech recognition", "konuşma tanıma", "konusma tanima",
                               "asr", "automatic speech recognition", "whisper"],
        "text to speech": ["text to speech", "tts", "metinden konuşmaya",
                           "speech synthesis"],
        "recommendation systems": ["recommendation systems", "recommender system",
                                   "öneri sistemleri", "oneri sistemleri",
                                   "collaborative filtering"],
        "ranking systems": ["ranking systems", "learning to rank", "ltr",
                            "sıralama sistemleri"],
        "anomaly detection": ["anomaly detection", "anomali tespiti",
                              "outlier detection", "aykırı değer tespiti"],
        "time series forecasting": ["time series forecasting", "zaman serisi tahmini",
                                    "time series prediction", "forecasting"],
        "graph neural networks": ["graph neural networks", "gnn", "graph ml",
                                  "grafik sinir ağları"],
        "federated learning": ["federated learning", "federasyonlu öğrenme",
                               "federated ml", "privacy preserving ml"],
        "model compression": ["model compression", "model sıkıştırma",
                              "knowledge distillation", "model distillation"],
        "quantization": ["quantization", "model quantization", "int8 quantization",
                         "nicemleme"],
        "pruning": ["model pruning", "network pruning", "sparse models"],  # yalın "pruning" FP
        "responsible ai": ["responsible ai", "sorumlu yapay zeka",
                           "ai ethics", "yapay zeka etiği", "fairness ml"],
        "ai safety": ["ai safety", "yapay zeka güvenliği", "alignment research"],
        "ai alignment": ["ai alignment", "llm alignment", "rlhf",
                         "reinforcement learning from human feedback"],
        "multimodal models": ["multimodal models", "multimodal ai", "multimodal learning",
                              "çok modlu modeller"],
        "vision language models": ["vision language models", "vlm", "visual llm",
                                   "image text models", "clip"],
    },
    # =====================================================================
    "Backend & API ⚙️": {
        "node.js": ["node.js", "nodejs", "node js"],
        "django": ["django"],
        "flask": ["flask"],
        "fastapi": ["fastapi", "fast api"],
        "spring": ["spring", "spring boot", "springboot"],
        "express": ["express", "expressjs", "express.js"],
        "nestjs": ["nestjs", "nest js", "nest.js"],
        "gin": ["gin framework", "gin gonic"],  # yalın "gin" → "begin" FP
        "echo": ["echo framework"],  # yalın "echo" jenerik
        "rest api": ["rest api", "restful", "rest ful", "rest servis"],
        "graphql": ["graphql", "graph ql"],
        "grpc": ["grpc"],
        "websocket": ["websocket", "websockets", "web socket"],
        "microservices": ["microservices", "mikroservis", "mikro servis"],
        "event driven architecture": ["event driven architecture",
                                      "event-driven architecture", "event driven",
                                      "olay güdümlü mimari"],
        "domain driven design": ["domain driven design", "domain-driven design", "ddd"],
        "cqrs": ["cqrs"],
        "celery": ["celery"],
        "message queue": ["message queue", "mesaj kuyruğu", "mesaj kuyrugu"],
        "api design": ["api design", "api tasarımı", "api tasarimi"],
        "oauth": ["oauth", "oauth2", "oauth 2.0"],
        "jwt": ["jwt", "json web token"],
        "rabbitmq": ["rabbitmq", "rabbit mq"],
    },
    # =====================================================================
    "Frontend & Mobil 🎨": {
        "react": ["react", "reactjs", "react.js"],
        "angular": ["angular", "angularjs"],
        "vue": ["vue", "vuejs", "vue.js"],
        "svelte": ["svelte", "sveltekit"],
        "next.js": ["next.js", "nextjs", "next js"],
        "nuxtjs": ["nuxtjs", "nuxt", "nuxt.js"],
        "redux": ["redux"],
        "zustand": ["zustand"],
        "react native": ["react native", "react-native"],
        "expo": ["expo"],
        "swiftui": ["swiftui", "swift ui"],
        "jetpack compose": ["jetpack compose", "jetpack"],
        "material ui": ["material ui", "material-ui"],
        "tailwind": ["tailwind", "tailwindcss", "tailwind css"],
        "webpack": ["webpack", "web pack"],
        "vite": ["vite"],
        "html": ["html", "html5"],
        "css": ["css", "css3"],
        "sass": ["sass", "scss"],
        "ui/ux": ["ui/ux", "ux", "ui", "kullanıcı deneyimi", "kullanici deneyimi"],
        "android": ["android"],
        "ios": ["ios"],
        "flutter": ["flutter"],
        "xcode": ["xcode", "xcode ide", "swift xcode"],
        "android studio": ["android studio", "android ide", "android sdk"],
        "fastlane": ["fastlane", "fastlane ios", "fastlane android"],
        "mobile analytics": ["mobile analytics", "mobil analitik",
                             "firebase analytics", "mixpanel"],
        "crash reporting": ["crash reporting", "crashlytics", "sentry mobile",
                            "firebase crashlytics"],
        "accessibility": ["accessibility", "erişilebilirlik", "a11y",
                          "wcag", "screen reader"],
        "deep linking": ["deep linking", "universal links", "app links",
                         "deferred deep link"],
        "push notifications": ["push notifications", "anlık bildirim",
                               "apns", "firebase fcm", "push notification"],
        "mobile security": ["mobile security", "mobil güvenlik",
                            "app shielding", "certificate pinning"],
    },
    # =====================================================================
    "Test & Kalite ✅": {
        "testing": ["unit testing", "integration testing", "automated testing",
                    "software testing", "commissioning and testing",
                    "test automation", "test otomasyonu"],
        "pytest": ["pytest", "py test"],
        "junit": ["junit", "j unit"],
        "testng": ["testng", "test ng"],
        "mocha": ["mocha"],
        "jasmine": ["jasmine"],
        "selenium": ["selenium", "selenium webdriver"],
        "appium": ["appium"],
        "postman": ["postman"],
        "k6": ["k6"],
        "jmeter": ["jmeter", "j meter", "apache jmeter"],
        "locust": ["locust"],
        "gatling": ["gatling"],
        "cypress": ["cypress"],
        "playwright": ["playwright"],
        "jest": ["jest"],
        "storybook": ["storybook", "story book"],
        "tdd": ["tdd", "test driven development", "test güdümlü geliştirme"],
        "bdd": ["bdd", "behavior driven development"],
        "contract testing": ["contract testing", "sözleşme testi"],
        "load testing": ["load testing", "yük testi", "yuk testi"],
        "chaos engineering": ["chaos engineering", "kaos mühendisliği"],
        "puppeteer": ["puppeteer", "headless chrome testing"],
        "rest assured": ["rest assured", "restassured", "rest-assured"],
        "karate framework": ["karate framework", "karate dsl"],
        "robot framework": ["robot framework", "robotframework"],
        "test planning": ["test planning", "test planlama", "test plan",
                          "test strategy", "test stratejisi"],
        "test management": ["test management", "test yönetimi"],
        "qtest": ["qtest", "q-test", "tricentis qtest"],
        "zephyr": ["zephyr scale", "zephyr squad", "zephyr for jira"],  # yalın "zephyr" RTOS ile karışır
        "exploratory testing": ["exploratory testing", "keşifsel test", "kesifsel test"],
        "regression testing": ["regression testing", "regresyon testi",
                               "regression test suite"],
        "performance testing": ["performance testing", "performans testi",
                                "performance test"],
        "security testing": ["security testing", "güvenlik testi", "guvenlik testi",
                             "application security testing"],
        "api testing": ["api testing", "api testi", "rest api testing"],
        "pact": ["pact testing", "pact framework", "pact contract"],  # yalın "pact" FP
    },
    # =====================================================================
    "DevOps & Platform 🔧": {
        "docker": ["docker"],
        "kubernetes": ["kubernetes", "k8s"],
        "aws": ["aws", "amazon web services"],
        "azure": ["azure", "microsoft azure"],
        "gcp": ["gcp", "google cloud", "google cloud platform"],
        "terraform": ["terraform"],
        "cloudformation": ["cloudformation", "cloud formation", "aws cfn"],
        "helm": ["helm", "helm chart"],
        "argocd": ["argocd", "argo cd"],
        "flux": ["fluxcd", "flux cd"],  # yalın "flux" → "influx" FP
        "istio": ["istio"],
        "service mesh": ["service mesh", "servis ağı", "servis agi"],
        "pulumi": ["pulumi"],
        "aws cdk": ["aws cdk"],  # yalın "cdk" kısa
        "crossplane": ["crossplane", "cross plane"],
        "vault": ["vault", "hashicorp vault"],
        "consul": ["consul", "hashicorp consul"],
        "packer": ["packer", "hashicorp packer"],
        "vagrant": ["vagrant"],
        "ansible": ["ansible"],
        "chef": ["chef infra", "chef cookbook"],  # yalın "chef" → aşçı FP
        "puppet": ["puppet"],  # "puppeteer" FP'si için kelime-sınırı (extractor)
        "saltstack": ["saltstack", "salt stack"],
        "jenkins": ["jenkins"],
        "gitlab ci": ["gitlab ci", "gitlab-ci", "gitlab ci/cd"],
        "github actions": ["github actions", "gh actions"],
        "circleci": ["circleci", "circle ci"],
        "travis ci": ["travis ci", "travis-ci", "travisci"],
        "ci/cd": ["ci/cd", "ci cd", "cicd", "continuous integration", "sürekli entegrasyon"],
        "git": ["git", "github", "gitlab", "version control", "sürüm kontrolü"],
        "linux": ["linux", "unix"],
        "sonarqube": ["sonarqube", "sonar qube", "sonarcloud"],
        "nexus": ["sonatype nexus", "nexus repository"],
        "artifactory": ["artifactory", "jfrog artifactory"],
        "harbor": ["harbor registry", "harbor container"],
        "datadog": ["datadog", "data dog"],
        "new relic": ["new relic", "newrelic"],
        "splunk": ["splunk"],
        "elk stack": ["elk stack"],
        "loki": ["loki", "grafana loki"],
        "jaeger": ["jaeger"],
        "opentelemetry": ["opentelemetry", "open telemetry"],
        "prometheus": ["prometheus"],
        "grafana": ["grafana"],
        "pagerduty": ["pagerduty", "pager duty"],
        "infrastructure as code": ["infrastructure as code", "iac",
                                   "kod olarak altyapı", "kod olarak altyapi"],
        "aws well architected": ["aws well architected", "well-architected framework",
                                 "aws waf"],
        "azure landing zones": ["azure landing zones", "azure landing zone",
                                "azure enterprise scale"],
        "multi cloud": ["multi cloud", "multicloud", "çoklu bulut", "coklu bulut",
                        "hybrid cloud"],
        "cloud cost optimization": ["cloud cost optimization", "bulut maliyet optimizasyonu",
                                    "cloud savings", "reserved instances"],
        "resilience engineering": ["resilience engineering", "dayanıklılık mühendisliği",
                                   "site reliability", "fault tolerance"],
        "open policy agent": ["open policy agent", "opa", "rego policy"],
        "policy as code": ["policy as code", "compliance as code"],  # yalın "pac" FP riski yüksek
        "service catalog": ["service catalog", "aws service catalog",
                            "servis kataloğu"],
        "drift detection": ["drift detection", "infrastructure drift",
                            "configuration drift"],
        "container security": ["container security", "konteyner güvenliği",
                               "image scanning", "runtime security"],
        "falco": ["falco", "sysdig falco", "falco rules"],
        "trivy": ["trivy", "aqua trivy", "container vulnerability scan"],
        "ebpf": ["ebpf", "extended bpf", "bpf networking"],
        "linux kernel": ["linux kernel", "kernel development", "kernel programming",
                         "linux internals"],
    },
    # =====================================================================
    "Güvenlik 🔒": {
        "cybersecurity": ["cybersecurity", "siber güvenlik", "siber guvenlik",
                          "information security", "cyber security"],
        "penetration testing": ["penetration testing", "pentest", "sızma testi", "sizma testi"],
        "owasp": ["owasp"],
        "sast": ["sast"],
        "dast": ["dast"],
        "devsecops": ["devsecops", "dev sec ops"],
        "cryptography": ["cryptography", "kriptografi", "şifreleme", "sifreleme"],
        "ssl/tls": ["ssl/tls", "ssl", "tls"],
        "gdpr": ["gdpr", "kvkk"],
        "soc2": ["soc2", "soc 2"],
        "iso 27001": ["iso 27001", "iso27001"],
        "zero trust": ["zero trust", "sıfır güven", "sifir guven"],
        "iam": ["iam", "identity and access management", "kimlik erişim yönetimi"],
        "rbac": ["rbac", "role based access control", "rol tabanlı erişim"],
        "secrets management": ["secrets management", "sır yönetimi", "sir yonetimi"],
        "vulnerability assessment": ["vulnerability assessment", "zafiyet taraması",
                                    "güvenlik açığı değerlendirme"],
        "burp suite": ["burp suite", "burpsuite", "portswigger burp"],
        "metasploit": ["metasploit", "metasploit framework"],
        "nmap": ["nmap", "network mapper", "port scanner"],
        "wireshark": ["wireshark", "packet capture", "paket analizi"],
        "kali linux": ["kali linux", "kali"],
        "ethical hacking": ["ethical hacking", "etik hackleme", "white hat hacking",
                            "certified ethical hacker", "ceh"],
        "soc analyst": ["soc analyst", "security operations center",
                        "soc tier 1", "güvenlik operasyon merkezi"],
        "threat hunting": ["threat hunting", "tehdit avı"],
        "incident response": ["incident response", "olaya müdahale",
                              "olaya mudahale", "ir plan"],
        "digital forensics": ["digital forensics", "dijital adli analiz",
                              "computer forensics", "dfir"],
        "malware analysis": ["malware analysis", "zararlı yazılım analizi",
                             "zararli yazilim analizi", "malware reverse"],
        "reverse engineering": ["reverse engineering", "tersine mühendislik",
                                "tersine muhendislik", "binary analysis"],
        "iast": ["iast", "interactive application security testing"],
        "pki certificates": ["pki", "public key infrastructure", "certificate management",
                             "x509", "sertifika yönetimi"],
        "nist framework": ["nist framework", "nist cybersecurity framework",
                           "nist sp 800"],
        "zero trust architecture": ["zero trust architecture", "ztna",
                                    "zero trust network access"],  # "zero trust" zaten var, mimari varyant
        "identity governance": ["identity governance", "iga", "identity lifecycle",
                                "kimlik yönetişimi"],
        "pam": ["pam", "privileged access management", "ayrıcalıklı erişim yönetimi"],
        "qradar": ["qradar", "ibm qradar", "ibm security qradar"],
        "microsoft sentinel": ["microsoft sentinel", "azure sentinel",
                               "ms sentinel"],
        "crowdstrike": ["crowdstrike", "crowdstrike falcon", "falcon edr"],
        "sentinelone": ["sentinelone", "sentinel one", "sentinel one edr"],
    },
    # =====================================================================
    "Sistem Tasarımı & Mimari 🏛️": {
        "system design": ["system design", "sistem tasarımı", "sistem tasarimi"],
        "distributed systems": ["distributed systems", "dağıtık sistemler",
                               "dagitik sistemler"],
        "high availability": ["high availability", "yüksek erişilebilirlik",
                             "yuksek erisilebilirlik"],
        "scalability": ["scalability", "ölçeklenebilirlik", "olceklenebilirlik"],
        "latency": ["latency", "gecikme"],
        "cap theorem": ["cap theorem", "cap teoremi"],
        "eventual consistency": ["eventual consistency", "nihai tutarlılık"],
        "circuit breaker": ["circuit breaker", "devre kesici"],
        "rate limiting": ["rate limiting", "hız sınırlama", "istek sınırlama"],
        "caching": ["caching", "önbellekleme", "onbellekleme", "cache"],
        "cdn": ["cdn", "content delivery network"],
        "load balancing": ["load balancing", "yük dengeleme", "load balancer"],
    },
    # =====================================================================
    "Metodoloji & Profesyonel 📋": {
        "agile": ["agile", "çevik", "cevik"],
        "scrum": ["scrum"],
        "kanban": ["kanban"],
        "devops": ["devops", "dev ops"],
        "gitops": ["gitops", "git ops"],
        "platform engineering": ["platform engineering", "platform mühendisliği"],
        "sre": ["sre", "site reliability engineering"],
        "mlops": ["mlops", "ml ops"],
        "dataops": ["dataops", "data ops"],
        "finops": ["finops", "fin ops"],
        "product management": ["product management", "ürün yönetimi", "urun yonetimi"],
        "technical writing": ["technical writing", "teknik yazım", "teknik dokümantasyon"],
        "code review": ["code review", "kod incelemesi", "kod review"],
        "mentoring": ["mentoring", "mentorluk"],
        "pair programming": ["pair programming", "eşli programlama", "esli programlama"],
    },
    # =====================================================================
    "Endüstriyel & Otomasyon 🏭": {
        "plc": ["plc", "programmable logic controller", "programlanabilir mantık denetleyicisi",
                "plc programlama", "plc programming"],
        "scada": ["scada", "supervisory control and data acquisition", "scada sistemi"],
        "hmi": ["hmi", "human machine interface", "insan makine arayüzü"],
        "dcs": ["dcs", "distributed control system", "dağıtık kontrol sistemi",
                "dagitik kontrol sistemi"],
        "iec 61131": ["iec 61131", "iec61131", "iec 61131-3"],
        "siemens s7": ["siemens s7", "s7-1500", "s7-300", "s7-400", "tia portal",
                       "siemens plc"],
        "allen bradley": ["allen bradley", "allen-bradley", "rockwell plc",
                          "controllogix", "compactlogix"],
        "rockwell automation": ["rockwell automation", "studio 5000", "factorytalk"],
        "labview": ["labview", "lab view", "ni labview", "national instruments labview"],
        "simulink": ["simulink", "matlab simulink"],
        "opc-ua": ["opc-ua", "opc ua", "opc unified architecture"],
        "modbus": ["modbus", "modbus rtu", "modbus tcp"],
        "profibus": ["profibus", "profinet"],
        "ethercat": ["ethercat", "ether cat"],
        "industrial iot": ["industrial iot", "iiot", "endüstriyel iot", "endustriyel iot"],
        "mes": ["mes", "manufacturing execution system", "üretim yürütme sistemi",
                "uretim yurutme sistemi"],
        "pid control": ["pid control", "pid controller", "pid kontrolü", "pid denetimi",
                        "pid tuning"],
        "ros": ["ros", "ros2", "robot operating system", "robot işletim sistemi"],
        "industrial robotics": ["industrial robotics", "endüstriyel robotik",
                                "endustriyel robotik"],
        "abb robotics": ["abb robotics", "abb robot", "abb rapid"],
        "fanuc": ["fanuc", "fanuc robotics", "fanuc cnc"],
        "kuka": ["kuka", "kuka robotics", "kuka krl"],
        "yaskawa": ["yaskawa", "yaskawa motoman"],
        "wonderware": ["wonderware", "aveva wonderware", "intouch scada"],
        "ignition scada": ["ignition scada", "ignition", "inductive automation"],  # yalın "ignition" FP
        "deltav": ["deltav", "delta v", "emerson deltav"],
        "honeywell dcs": ["honeywell dcs", "honeywell experion", "experion pks"],
        "ethernet/ip": ["ethernet/ip", "ethernetip", "ethernet ip protocol"],
        "devicenet": ["devicenet", "device net"],
        "as-interface": ["as-interface", "as interface", "asi bus"],
        "functional safety": ["functional safety", "fonksiyonel güvenlik",
                              "fonksiyonel guvenlik"],
        "sil": ["sil", "safety integrity level", "güvenlik bütünlük seviyesi"],
        "iec 61508": ["iec 61508", "iec61508"],
        "atex": ["atex", "atex directive", "ex zone", "patlama koruması"],
        "motion control": ["motion control", "hareket kontrolü", "hareket kontrolu"],
        "servo systems": ["servo systems", "servo motor", "servo sürücü", "servo surucu"],
        "vfd": ["vfd", "variable frequency drive", "frekans invertörü", "frekans invertoru",
                "inverter drive"],
        "motor drives": ["motor drives", "motor sürücü", "motor surucu", "ac drive"],
        "plc ladder logic": ["ladder logic", "ladder diagram", "merdiven diyagramı",
                             "merdiven diyagrami"],
        "structured text": ["structured text", "yapısal metin", "iec st programming"],
        "function block diagram": ["function block diagram", "fbd", "fonksiyon blok diyagramı"],
    },
    # =====================================================================
    "Mekanik & Tasarım ⚙️": {
        "solidworks": ["solidworks", "solid works"],
        "catia": ["catia", "catia v5", "catia v6"],
        "autocad": ["autocad", "auto cad", "autodesk autocad"],
        "ansys": ["ansys", "ansys mechanical", "ansys fluent", "ansys workbench"],
        "autodesk inventor": ["autodesk inventor", "inventor cad"],  # yalın "inventor" FP
        "fusion 360": ["fusion 360", "autodesk fusion", "fusion360"],
        "siemens nx": ["siemens nx", "nx cad", "unigraphics", "ug nx"],  # yalın "nx" FP
        "pro engineer": ["pro engineer", "pro-e", "proe", "ptc pro-e"],
        "hypermesh": ["hypermesh", "altair hypermesh"],
        "abaqus": ["abaqus", "simulia abaqus"],
        "fea": ["finite element analysis", "sonlu elemanlar analizi",
                "finite element method", "fem"],  # yalın "fea" FP riski yüksek
        "cfd": ["cfd", "computational fluid dynamics", "hesaplamalı akışkanlar dinamiği",
                "hesaplamali akiskanlar dinamigi"],
        "cad cam": ["cad cam", "cad/cam", "computer aided manufacturing"],
        "3d printing": ["3d printing", "3d baskı", "3d baski", "additive manufacturing",
                        "eklemeli üretim", "eklemeli uretim"],
        "gd&t": ["gd&t", "gdt", "geometric dimensioning and tolerancing",
                 "geometrik boyutlandırma ve tolerans"],
        "creo": ["creo", "ptc creo", "creo parametric"],
        "cnc programming": ["cnc programming", "cnc programlama", "g-code", "g code",
                            "fanuc cnc programming"],
        "tolerance analysis": ["tolerance analysis", "tolerans analizi"],
        "lean manufacturing": ["lean manufacturing", "yalın üretim", "yalin uretim"],
        "six sigma": ["six sigma", "6 sigma", "altı sigma", "alti sigma", "dmaic"],
        "kaizen": ["kaizen", "sürekli iyileştirme", "surekli iyilestirme"],
        "failure analysis": ["failure analysis", "arıza analizi", "ariza analizi"],
        "fatigue analysis": ["fatigue analysis", "yorulma analizi", "fatigue life"],
        "composite materials": ["composite materials", "kompozit malzeme",
                                "carbon fiber", "karbon fiber"],
        "metallurgy": ["metallurgy", "metalurji", "materials science", "malzeme bilimi"],
        "asme standards": ["asme", "asme standards", "asme code"],
        "din standards": ["din standards", "din normu", "din spec"],
        "hydraulics": ["hydraulics", "hidrolik", "hydraulic systems", "hidrolik sistemler"],
        "pneumatics": ["pneumatics", "pnömatik", "pneumatik", "pnomatik",
                       "pneumatic systems"],
        "vibration analysis": ["vibration analysis", "titreşim analizi", "modal analysis",
                               "titresim analizi"],
        "tribology": ["tribology", "triboloji", "lubrication", "yağlama"],
        "injection molding": ["injection molding", "enjeksiyon kalıplama",
                              "enjeksiyon kaliplama", "plastic injection"],
        "die casting": ["die casting", "basınçlı döküm", "basinçli döküm"],
        "welding engineering": ["welding engineering", "kaynak mühendisliği",
                                "kaynak muhendisligi", "weld inspection"],
        "ndt testing": ["ndt", "ndt testing", "non-destructive testing",
                        "tahribatsız muayene", "tahribatsiz muayene"],
    },
    # =====================================================================
    "Elektrik & Elektronik ⚡": {
        "altium designer": ["altium designer", "altium", "altium pcb"],
        "kicad": ["kicad", "ki cad"],
        "eagle cad": ["eagle cad", "autodesk eagle"],  # yalın "eagle" FP
        "pspice": ["pspice", "p-spice", "orcad pspice"],
        "multisim": ["multisim", "ni multisim"],
        "fpga": ["fpga", "field programmable gate array"],
        "vhdl": ["vhdl"],
        "verilog": ["verilog", "system verilog", "systemverilog"],
        "oscilloscope": ["oscilloscope", "osiloskop", "digital oscilloscope"],
        "pcb design": ["pcb design", "pcb layout", "pcb tasarımı", "pcb tasarimi",
                       "printed circuit board"],
        "power systems": ["power systems", "güç sistemleri", "guc sistemleri",
                          "electrical power"],
        "etap": ["etap", "electrical transient analyzer"],
        "eplan": ["eplan", "eplan electric", "eplan p8"],
        "autocad electrical": ["autocad electrical"],
        "protection relay": ["protection relay", "koruma rölesi", "relay protection",
                             "differential relay"],
        "switchgear design": ["switchgear design", "anahtarlama teçhizatı", "switchgear",
                              "mv switchgear", "lv switchgear"],
        "power transformer": ["power transformer", "güç trafosu", "guc trafosu",
                              "transformer design"],
        "substation design": ["substation design", "trafo merkezi tasarımı",
                              "substation engineering"],
        "high voltage engineering": ["high voltage engineering", "yüksek gerilim",
                                     "yuksek gerilim", "hv engineering"],
        "low voltage design": ["low voltage design", "alçak gerilim", "alcak gerilim",
                               "lv design"],
        "energy management": ["energy management", "enerji yönetimi", "enerji yonetimi",
                              "energy efficiency"],
        "renewable energy": ["renewable energy", "yenilenebilir enerji",
                             "yenilenebilir enerji sistemleri"],
        "solar pv design": ["solar pv design", "solar pv", "fotovoltaik tasarım",
                            "fotovoltaik tasarim", "pv system design"],
        "wind turbine": ["wind turbine", "rüzgar türbini", "ruzgar turbini",
                         "wind energy"],
        "grid connection": ["grid connection", "şebeke bağlantısı", "sebeke baglantisi",
                            "grid integration"],
        "power quality": ["power quality", "güç kalitesi", "guc kalitesi",
                          "harmonics analysis"],
        "load flow analysis": ["load flow analysis", "yük akışı analizi",
                               "load flow", "power flow analysis"],
        "short circuit analysis": ["short circuit analysis", "kısa devre analizi",
                                   "kisa devre analizi", "fault analysis"],
        "arc flash": ["arc flash", "ark flaşı", "arc flash analysis"],
        "cable sizing": ["cable sizing", "kablo boyutlandırma", "kablo boyutlandirma",
                         "cable design"],
        "electrical drawings": ["electrical drawings", "elektrik çizimleri",
                                "elektrik cizimleri", "single line diagram"],
    },
    # =====================================================================
    "İnşaat & Yapı 🏗️": {
        "revit": ["revit", "autodesk revit"],
        "bim": ["bim", "building information modeling", "yapı bilgi modellemesi",
                "yapi bilgi modellemesi"],
        "autocad civil 3d": ["autocad civil 3d", "civil 3d", "autodesk civil 3d"],
        "staad pro": ["staad pro", "staad.pro", "bentley staad"],
        "sap2000": ["sap2000", "sap 2000", "csi sap2000"],
        "etabs": ["etabs", "csi etabs"],
        "arcgis": ["arcgis", "arc gis", "esri arcgis"],  # yalın "gis" FP: logistics, register vb.
        "primavera": ["primavera", "oracle primavera", "primavera p6", "p6"],
        "navisworks": ["navisworks", "autodesk navisworks"],
        "sketchup": ["sketchup", "sketch up", "trimble sketchup"],
        "robot structural analysis": ["robot structural analysis", "robot structural",
                                      "autodesk robot"],
        "geotechnical engineering": ["geotechnical engineering", "geoteknik mühendisliği",
                                     "geoteknik muhendisligi", "geotechnics"],
        "soil mechanics": ["soil mechanics", "zemin mekaniği", "zemin mekanigi"],
        "foundation design": ["foundation design", "temel tasarımı", "temel tasarimi",
                              "deep foundation"],
        "pile design": ["pile design", "kazık tasarımı", "kazik tasarimi",
                        "piling engineering"],
        "traffic engineering": ["traffic engineering", "trafik mühendisliği",
                                "trafik muhendisligi"],
        "road design": ["road design", "yol tasarımı", "yol tasarimi",
                        "highway design", "pavement design"],
        "hydraulic engineering": ["hydraulic engineering", "hidrolik mühendisliği",
                                  "hidrolik muhendisligi"],
        "water supply": ["water supply", "su temin sistemi", "water distribution"],
        "wastewater treatment": ["wastewater treatment", "atıksu arıtma",
                                 "atiksu aritma", "sewage treatment"],
        "dam design": ["dam design", "baraj tasarımı", "baraj tasarimi"],
        "environmental impact assessment": ["environmental impact assessment", "eia",
                                            "çed", "çevresel etki değerlendirmesi"],
        "quantity surveying": ["quantity surveying", "metraj", "keşif",
                               "bill of quantities", "bq"],
        "ms project": ["ms project", "microsoft project", "microsoft proje"],
        "cost estimation": ["cost estimation", "maliyet tahmini", "cost estimate",
                            "project cost"],
    },
    # =====================================================================
    "Kimya & Proses 🧪": {
        "aspen hysys": ["aspen hysys", "hysys", "aspentech hysys"],
        "aspen plus": ["aspen plus", "aspenplus", "aspentech plus"],
        "chemcad": ["chemcad", "chem cad"],
        "process simulation": ["process simulation", "proses simülasyonu",
                               "proses simulasyonu"],
        "piping": ["piping", "pipe design", "boru tesisatı", "boru tesisati"],
        "hazop": ["hazop", "hazard and operability study", "tehlike ve işletilebilirlik"],
        "p&id": ["p&id", "piping and instrumentation diagram",
                 "boru ve enstrüman diyagramı", "boru ve enstruman diyagrami"],
        "distillation": ["distillation", "damıtma", "damitma"],
        "heat transfer": ["heat transfer", "ısı transferi", "isi transferi",
                          "heat exchanger", "ısı eşanjörü"],
        "petroleum refining": ["petroleum refining", "petrol rafinasyonu",
                               "refinery engineering"],
        "process safety management": ["process safety management", "psm",
                                      "proses güvenlik yönetimi"],
        "lopa": ["lopa", "layer of protection analysis", "koruma katmanı analizi"],
        "distillation column": ["distillation column", "damıtma kolonu",
                                "damitma kolonu", "fractionation column"],
        "heat exchanger design": ["heat exchanger design", "ısı eşanjörü tasarımı",
                                  "isi esanjoru tasarimi", "shell and tube"],
        "reactor design": ["reactor design", "reaktör tasarımı", "reaktor tasarimi",
                           "chemical reactor"],
        "polymer engineering": ["polymer engineering", "polimer mühendisliği",
                                "polimer muhendisligi", "plastics engineering"],
        "pharmaceutical manufacturing": ["pharmaceutical manufacturing",
                                         "ilaç üretimi", "ilac uretimi",
                                         "pharma manufacturing"],
        "gmp": ["gmp", "good manufacturing practice", "iyi üretim uygulamaları",
                "iyi uretim uygulamalari"],
        "food processing": ["food processing", "gıda işleme", "gida isleme",
                            "food engineering", "gıda mühendisliği"],
        "water treatment": ["water treatment", "su arıtma", "su aritma",
                            "water purification"],
        "environmental engineering": ["environmental engineering", "çevre mühendisliği",
                                      "cevre muhendisligi"],
        "waste management": ["waste management", "atık yönetimi", "atik yonetimi",
                             "waste treatment"],
    },
    # =====================================================================
    "Sağlık & Biyomedikal 🏥": {
        "hl7": ["hl7", "health level 7"],
        "fhir": ["fhir", "fast healthcare interoperability resources"],
        "dicom": ["dicom", "digital imaging and communications in medicine"],
        "iso 13485": ["iso 13485", "iso13485"],
        "fda regulations": ["fda regulations", "fda approval", "fda compliance"],
        "510k": ["510k", "510(k)"],
        "medical imaging": ["medical imaging", "tıbbi görüntüleme", "tibbi goruntuleme"],
        "clinical trials": ["clinical trials", "klinik çalışmalar", "klinik calisma",
                            "klinik deney"],
        "ce marking": ["ce marking", "ce işareti", "ce belgesi", "ce certification"],
        "mdr": ["mdr", "medical device regulation", "tıbbi cihaz yönetmeliği"],
        "iso 14971": ["iso 14971", "risk management medical devices",
                      "tıbbi cihaz risk yönetimi"],
        "iec 62304": ["iec 62304", "medical device software lifecycle"],
        "good clinical practice": ["gcp guidelines", "good clinical practice", "ich gcp"],  # "gcp" → GCP cloud ile çakışır
        "ich guidelines": ["ich guidelines", "ich q10", "ich e6"],
        "epic ehr": ["epic ehr", "epic system", "epic emr"],  # yalın "epic" FP
        "cerner": ["cerner", "cerner millennium", "cerner ehr"],
        "emr ehr systems": ["emr ehr", "electronic medical records",
                            "electronic health records", "elektronik sağlık kaydı"],
        "pacs systems": ["pacs", "pacs system", "picture archiving",
                         "görüntü arşivleme sistemi"],
        "radiology informatics": ["radiology informatics", "radyoloji bilişimi",
                                  "ris system"],
        "clinical decision support": ["clinical decision support", "cdss",
                                      "klinik karar destek sistemi"],
        "telehealth": ["telehealth", "telesağlık", "telemedicine",
                       "uzaktan sağlık hizmetleri", "remote patient monitoring"],
        "wearable integration": ["wearable integration", "wearable technology",
                                 "apple healthkit", "google health",
                                 "giyilebilir teknoloji entegrasyonu"],
        "clinical nlp": ["clinical nlp", "biomedical nlp", "medical text mining",
                         "clinical text processing"],
        "medical coding": ["medical coding", "icd-10", "icd10", "cpt codes",
                           "tıbbi kodlama"],
    },
    # =====================================================================
    "Otomotiv & Gömülü 🚗": {
        "autosar": ["autosar", "autosar classic", "autosar adaptive"],
        "can bus": ["can bus", "can protocol", "controller area network"],
        "lin bus": ["lin bus", "lin protocol", "local interconnect network"],
        "flexray": ["flexray", "flex ray"],
        "iso 26262": ["iso 26262", "functional safety automotive", "otomotiv fonksiyonel güvenlik"],
        "misra c": ["misra c", "misra c++", "misra coding standard"],
        "ecu development": ["ecu development", "ecu yazılımı", "electronic control unit"],
        "hil testing": ["hil testing", "hil", "hardware in the loop",
                        "donanım döngüde test"],
        "mil testing": ["mil testing", "model in the loop",
                        "model döngüde test"],  # yalın "mil" FP riski yüksek
        "sil testing": ["sil testing", "software in the loop",
                        "yazılım döngüde test"],  # SIL(güvenlik)≠SIL(oto) — farklı canonical
        "adas": ["adas", "advanced driver assistance systems",
                 "gelişmiş sürücü destek sistemleri"],
        "autonomous driving": ["autonomous driving", "otonom sürüş", "self-driving",
                               "level 2 autonomy", "level 4 autonomy"],
        "v2x": ["v2x", "vehicle to everything", "vehicle to vehicle", "v2v", "v2i"],
        "dspace": ["dspace", "d-space", "dspace targetlink"],
        "vector tools": ["vector tools", "vectorcast", "canoe", "canalyzer"],
        "capl": ["capl", "capl scripting", "can access programming language"],
        "uds protocol": ["uds protocol", "uds", "unified diagnostic services",
                         "iso 14229"],
        "obd diagnostics": ["obd", "obd-ii", "obd diagnostics", "on-board diagnostics"],
    },
    # =====================================================================
    "Ağ & Altyapı 🌐": {
        "cisco ios": ["cisco ios", "cisco networking", "cisco ccna", "cisco ccnp"],
        "juniper networks": ["juniper networks", "juniper", "junos"],
        "fortinet": ["fortinet", "fortigate", "fortios"],
        "palo alto networks": ["palo alto networks", "palo alto firewall", "panorama"],
        "bgp": ["bgp", "border gateway protocol"],
        "ospf": ["ospf", "open shortest path first"],
        "mpls": ["mpls", "multiprotocol label switching"],
        "sd-wan": ["sd-wan", "sdwan", "software defined wan"],
        "vxlan": ["vxlan", "vx lan", "virtual extensible lan"],
        "network security": ["network security", "ağ güvenliği", "ag guvenligi"],
        "firewall management": ["firewall management", "firewall", "güvenlik duvarı",
                                "guvenlik duvari"],
        "ids/ips": ["ids ips", "ids/ips", "intrusion detection",
                    "intrusion prevention", "saldırı tespit sistemi"],
        "siem": ["siem", "security information and event management",
                 "güvenlik olayı yönetimi"],
        "nac": ["nac", "network access control", "ağ erişim kontrolü"],
        "wifi design": ["wifi design", "wireless design", "wlan design",
                        "kablosuz ağ tasarımı"],
        "5g networks": ["5g networks", "5g", "5g nr", "5g infrastructure"],
        "iot networking": ["iot networking", "iot network", "nesnelerin interneti ağı"],
        "voip": ["voip", "voice over ip", "ip telefon", "ip telephony"],
        "network monitoring": ["network monitoring", "ağ izleme", "ag izleme",
                               "network management"],
        "snmp": ["snmp", "simple network management protocol"],
        "netflow": ["netflow", "net flow", "ipfix", "network traffic analysis"],
    },
    # =====================================================================
    "Finans & İş 💼": {
        "bloomberg terminal": ["bloomberg terminal", "bloomberg", "bloomberg professional"],
        "vba excel": ["vba excel", "vba", "visual basic for applications",
                      "excel vba", "excel makro"],
        "financial modeling": ["financial modeling", "finansal modelleme",
                               "financial model"],
        "dcf analysis": ["dcf analysis", "dcf", "discounted cash flow",
                         "indirgenmiş nakit akışı"],
        "value at risk": ["value at risk", "var model", "market risk var"],  # yalın "var" FP
        "stress testing": ["stress testing", "stres testi", "scenario analysis"],
        "basel iii": ["basel iii", "basel 3", "capital adequacy", "sermaye yeterliliği"],
        "fix protocol": ["fix protocol", "financial information exchange",
                         "fix messaging"],
        "algorithmic trading": ["algorithmic trading", "algo trading",
                                "algoritmik işlem", "quant trading"],
        "options pricing": ["options pricing", "opsiyon fiyatlama",
                            "black scholes", "derivatives pricing"],
        "derivatives": ["derivatives", "türev araçlar", "turev araclar",
                        "financial derivatives"],
        "sap finance": ["sap finance", "sap fico", "sap fi", "sap co"],
        "oracle financials": ["oracle financials", "oracle erp finance",
                              "oracle fusion financials"],
        "ifrs": ["ifrs", "uluslararası finansal raporlama standartları",
                 "international financial reporting standards"],
        "gaap": ["gaap", "us gaap", "generally accepted accounting principles"],
        "sox compliance": ["sox compliance", "sox", "sarbanes-oxley",
                           "iç kontrol", "ic kontrol"],
    },
    # =====================================================================
    "Kalite & Standartlar 🎯": {
        "iso 9001": ["iso 9001", "iso9001", "kalite yönetim sistemi",
                     "quality management system"],
        "iso 14001": ["iso 14001", "iso14001", "çevre yönetim sistemi",
                      "environmental management system"],
        "iso 45001": ["iso 45001", "iş güvenliği yönetim sistemi",
                      "occupational health and safety"],
        "iatf 16949": ["iatf 16949", "iatf16949", "otomotiv kalite standardı"],
        "as9100": ["as9100", "havacılık kalite standardı", "aerospace quality"],
        "fmea": ["fmea", "failure mode and effects analysis",
                 "hata türleri ve etkileri analizi"],
        "apqp": ["apqp", "advanced product quality planning",
                 "gelişmiş ürün kalite planlaması"],
        "ppap": ["ppap", "production part approval process",
                 "üretim parçası onay süreci"],
        "spc": ["spc", "statistical process control", "istatistiksel proses kontrolü"],
        "msa": ["msa", "measurement system analysis", "ölçüm sistemi analizi"],
        "root cause analysis": ["root cause analysis", "kök neden analizi",
                                "rca", "ishikawa", "5 why", "5 neden"],
        "8d methodology": ["8d methodology", "8d report", "8d problem solving",
                           "sekiz disiplin"],
        "5s": ["5s methodology", "5s workplace", "5s sistemi", "sort set shine"],  # yalın "5s" FP
        "value stream mapping": ["value stream mapping", "vsm", "değer akışı haritalama"],
        "audit management": ["audit management", "denetim yönetimi", "internal audit",
                             "iç denetim"],
        "capa": ["corrective and preventive action"],  # yalın "capa" FP riski yüksek (capabilities vb.)
    },
    # =====================================================================
    "Proje Yönetimi 📋": {
        "pmp": ["pmp", "project management professional"],
        "prince2": ["prince2", "prince 2", "prince2 practitioner"],
        "agile pm": ["agile pm", "agile project management",
                     "çevik proje yönetimi"],  # "agile" Metodoloji'de var, "agile pm" farklı canonical
        "safe agile": ["safe agile", "scaled agile", "safe framework", "safe 5.0"],
        "earned value management": ["earned value management", "evm",
                                    "kazanılmış değer yönetimi"],
        "risk management": ["risk management", "risk yönetimi", "risk assessment",
                            "risk değerlendirmesi"],
        "change management": ["change management", "değişim yönetimi",
                              "organizational change"],
        "stakeholder management": ["stakeholder management", "paydaş yönetimi"],
        "scope management": ["scope management", "kapsam yönetimi"],
        "resource planning": ["resource planning", "kaynak planlaması",
                              "resource management"],
    },
    # =====================================================================
    "Yazılım Mimarisi & Desenler 📐": {
        # Mevcut: microservices, cqrs, domain driven design, circuit breaker,
        #         service mesh, api gateway, event driven architecture → atlandı
        "event sourcing": ["event sourcing", "olay kaynağı", "olay kaynagi",
                           "event store"],
        "saga pattern": ["saga pattern", "saga", "distributed saga",
                         "choreography saga", "orchestration saga"],
        "strangler fig pattern": ["strangler fig", "strangler fig pattern",
                                  "strangler pattern"],
        "hexagonal architecture": ["hexagonal architecture", "ports and adapters",
                                   "altıgen mimari", "altiegen mimari"],
        "clean architecture": ["clean architecture", "temiz mimari",
                               "uncle bob architecture"],
        "solid principles": ["solid principles", "solid", "single responsibility",
                             "open closed principle"],
        "design patterns": ["design patterns", "tasarım desenleri", "tasarim desenleri",
                            "gang of four", "gof patterns"],
        "api gateway pattern": ["api gateway pattern", "api gateway architecture",
                                "backend for frontend", "bff pattern"],
        "sidecar pattern": ["sidecar pattern", "sidecar proxy", "ambassador pattern"],
        "bulkhead pattern": ["bulkhead pattern", "bulkhead isolation", "bölme deseni"],
        "retry pattern": ["retry pattern", "retry logic", "exponential backoff",
                          "yeniden deneme deseni"],
        "outbox pattern": ["outbox pattern", "transactional outbox",
                           "inbox outbox pattern"],
    },
    # =====================================================================
    "Veritabanı Yönetimi & DBA 💾": {
        # Mevcut DB teknolojileri (oracle, postgresql vb.) Veritabanları 🗄️'de → atlandı
        "oracle dba": ["oracle dba", "oracle administration", "oracle rac",
                       "oracle exadata"],
        "sql server dba": ["sql server dba", "mssql dba", "sql server administration",
                           "sql server agent"],
        "mysql dba": ["mysql dba", "mysql administration", "mysql replication"],
        "postgresql administration": ["postgresql administration", "postgres dba",
                                      "postgres administration", "pg admin"],
        "mongodb administration": ["mongodb administration", "mongodb dba",
                                   "mongo atlas", "mongodb ops manager"],
        "redis cluster": ["redis cluster", "redis sentinel", "redis replication"],
        "cassandra administration": ["cassandra administration", "cassandra dba",
                                     "cassandra ops"],
        "column store database": ["column store", "columnar database",
                                  "columnar storage"],  # clickhouse spesifik zaten var
        "time series database": ["time series database", "tsdb",
                                 "zaman serisi veritabanı"],  # influxdb spesifik var
        "graph database": ["graph database", "graf veritabanı", "graf veritabani",
                           "property graph"],  # neo4j spesifik var
        "document store": ["document store", "document database",
                           "döküman veritabanı"],  # mongodb genel, bu kavramsal
        "data modeling": ["data modeling", "veri modelleme", "eer diagram",
                          "entity relationship", "er diagram"],
        "database design": ["database design", "veritabanı tasarımı",
                            "veritabani tasarimi", "schema design"],
        "replication": ["database replication", "veri replikasyonu",
                        "master slave replication", "read replica"],
        "sharding": ["sharding", "database sharding", "yatay bölümleme",
                     "horizontal partitioning"],
        "partitioning": ["partitioning", "table partitioning", "bölümleme",
                         "range partitioning", "hash partitioning"],
        "backup recovery": ["backup recovery", "database backup", "yedekleme kurtarma",
                            "point in time recovery", "pitr"],
        "database performance tuning": ["database performance tuning",
                                        "db performance", "veritabanı performans",
                                        "query tuning"],
        "query optimization": ["query optimization", "sorgu optimizasyonu",
                               "execution plan", "explain plan"],
        "index design": ["index design", "indeks tasarımı", "indeks tasarimi",
                         "composite index", "covering index"],
    },
    # =====================================================================
    "Oyun & Grafik 🎮": {
        "unity3d": ["unity3d", "unity 3d", "unity game engine"],
        "unreal engine": ["unreal engine", "ue5", "ue4", "unreal"],
        "godot": ["godot", "godot engine", "gdscript"],
        "opengl": ["opengl", "open gl", "opengl es"],
        "vulkan": ["vulkan", "vulkan api"],
        "directx": ["directx", "direct3d", "dx12", "dx11"],
        "metal": ["metal api", "apple metal"],  # yalın "metal" → malzeme FP
        "shader programming": ["shader programming", "shader development",
                               "gölgelendirici programlama"],
        "hlsl": ["hlsl", "high level shading language", "directx shader"],
        "glsl": ["glsl", "opengl shading language"],
        "game physics": ["game physics", "physics engine", "oyun fiziği",
                         "bullet physics", "physx"],
        "pathfinding": ["pathfinding", "a star algorithm", "navmesh",
                        "yol bulma algoritması"],
        "procedural generation": ["procedural generation", "procedural content",
                                  "prosedürel üretim"],
        "3d modeling": ["3d modeling", "3d modelleme", "3d asset creation"],
        "blender": ["blender", "blender 3d"],
        "maya": ["maya", "autodesk maya"],
        "3ds max": ["3ds max", "3d studio max", "autodesk 3ds max"],
        "rigging animation": ["rigging", "character animation", "skeletal animation",
                              "rig ve animasyon"],
        "vfx": ["vfx", "visual effects", "görsel efektler", "particle systems"],
        "game design": ["game design", "oyun tasarımı", "game mechanics",
                        "game balancing"],
        "level design": ["level design", "seviye tasarımı", "environment design"],
        "ar vr": ["ar vr", "augmented reality", "virtual reality", "mixed reality",
                  "xr", "arkit", "arcore", "artırılmış gerçeklik", "sanal gerçeklik"],
        "unity ecs": ["unity ecs", "entity component system", "dots unity"],
        "game networking": ["game networking", "multiplayer networking",
                            "netcode", "çok oyunculu ağ"],
        "photon": ["photon engine", "photon fusion", "photon pun"],
    },
    # =====================================================================
    "Ses & Medya 🎵": {
        "audio processing": ["audio processing", "ses işleme",
                             "digital audio", "dsp audio"],
        "signal processing": ["signal processing", "sinyal işleme",
                              "digital signal processing", "dsp"],
        "ffmpeg": ["ffmpeg", "ff mpeg", "ffprobe"],
        "gstreamer": ["gstreamer", "gst pipeline"],
        "webrtc": ["webrtc", "web rtc", "real-time communication",
                   "gerçek zamanlı iletişim"],
        "hls": ["hls", "http live streaming", "adaptive bitrate",
                "dash streaming"],
        "video encoding": ["video encoding", "video kodlama",
                           "h264", "h265", "hevc", "av1", "codec"],
        "streaming architecture": ["streaming architecture", "akış mimarisi",
                                   "live streaming", "vod streaming"],
        "voice cloning": ["voice cloning", "ses klonlama",
                          "voice synthesis", "neural tts"],
        "audio fingerprinting": ["audio fingerprinting", "ses parmak izi",
                                 "content recognition", "shazam api"],
        "content delivery": ["content delivery", "içerik dağıtımı",
                             "cdn media", "media delivery network"],
    },
    # =====================================================================
    "Blockchain & Web3 ⛓️": {
        "solidity": ["solidity", "solidity smart contract"],
        "ethereum": ["ethereum", "eth", "evm", "ethereum blockchain"],
        "web3.js": ["web3.js", "web3js", "ethers.js", "ethersjs"],
        "smart contracts": ["smart contracts", "akıllı sözleşmeler",
                            "akilli sozlesmeler", "on-chain logic"],
        "defi": ["defi", "decentralized finance", "merkeziyetsiz finans",
                 "yield farming", "liquidity pools"],
        "nft": ["nft", "non-fungible token", "erc-721", "erc-1155",
                "nft marketplace"],
        "consensus mechanisms": ["consensus mechanisms", "uzlaşma mekanizmaları",
                                 "proof of stake", "proof of work"],  # yalın "pos" FP, "consensus" tek başına çok geniş
        "ipfs": ["ipfs", "interplanetary file system", "decentralized storage"],
        "hyperledger fabric": ["hyperledger fabric", "hyperledger",
                               "enterprise blockchain", "fabric chaincode"],
        "tokenomics": ["tokenomics", "token economics", "token tasarımı"],
        "dao governance": ["dao", "decentralized autonomous organization",
                           "on-chain governance"],
    },
    # =====================================================================
    "E-Ticaret & ERP 🛒": {
        "shopify": ["shopify", "shopify plus", "shopify liquid"],
        "woocommerce": ["woocommerce", "woo commerce"],
        "magento": ["magento", "adobe commerce", "magento 2"],
        "stripe": ["stripe", "stripe payments", "stripe api"],
        "paypal": ["paypal", "paypal sdk", "braintree"],
        "inventory management": ["inventory management", "envanter yönetimi",
                                 "warehouse management", "wms"],
        "sap": ["sap", "sap s/4hana", "sap ecc", "sap basis"],  # sap finance ayrı var
        "microsoft dynamics": ["microsoft dynamics", "dynamics 365",
                               "dynamics crm", "dynamics erp"],
        "supply chain management": ["supply chain management", "tedarik zinciri yönetimi",
                                    "supply chain", "scm"],
        "demand forecasting": ["demand forecasting", "talep tahmini",
                               "sales forecasting", "demand planning"],
        "crm salesforce": ["salesforce", "salesforce crm", "sfdc",
                           "salesforce admin"],
        "hubspot": ["hubspot", "hubspot crm", "hubspot marketing"],
        "marketo": ["marketo", "adobe marketo", "marketing automation"],
    },
    # =====================================================================
    "Arama & İçerik 🔍": {
        "solr": ["solr", "apache solr", "solr search"],
        "search relevance": ["search relevance", "arama alaka düzeyi",
                             "ranking tuning", "query understanding"],
        "content management": ["content management", "içerik yönetimi",
                               "cms platform"],
        "drupal": ["drupal", "drupal cms"],
        "wordpress": ["wordpress", "wordpress development", "wp", "elementor"],
        "headless cms": ["headless cms", "contentful", "sanity cms",
                         "strapi", "headless content"],
        "seo technical": ["seo technical", "teknik seo", "core web vitals",
                          "schema markup", "structured data"],
    },
    # =====================================================================
    "Tarım & Enerji 🌿": {
        "precision agriculture": ["precision agriculture", "hassas tarım",
                                  "hassas tarim", "smart farming"],
        "drone technology": ["drone technology", "insansız hava aracı",
                             "uav", "drone mapping"],
        "iot sensors": ["iot sensors", "iot sensörü", "sensor integration",
                        "sensor fusion"],
        "crop monitoring": ["crop monitoring", "bitki izleme",
                            "remote sensing agriculture", "ndvi"],
        "energy audit": ["energy audit", "enerji denetimi",
                         "iso 50001", "energy assessment"],
        "carbon footprint": ["carbon footprint", "karbon ayak izi",
                             "ghg accounting", "scope 1 2 3"],
        "life cycle assessment": ["life cycle assessment", "lca",
                                  "yaşam döngüsü değerlendirmesi"],
        "battery technology": ["battery technology", "pil teknolojisi",
                               "lithium ion", "battery management system", "bms"],
        "smart grid": ["smart grid", "akıllı şebeke", "akilli sebeke",
                       "demand response", "grid modernization"],
        "building energy management": ["building energy management", "bems",
                                       "bina enerji yönetimi", "energy monitoring"],
    },
    # =====================================================================
    "İş Teknolojileri ⚖️": {
        "contract analysis": ["contract analysis", "sözleşme analizi",
                              "contract review", "legal document analysis"],
        "ediscovery": ["ediscovery", "e-discovery", "electronic discovery",
                       "litigation support"],
        "compliance management": ["compliance management", "uyum yönetimi",
                                  "regulatory compliance", "mevzuat uyumu"],
        "privacy engineering": ["privacy engineering", "gizlilik mühendisliği",
                                "privacy by design", "data privacy"],
        "workday": ["workday", "workday hris", "workday hcm"],
        "applicant tracking": ["applicant tracking", "ats", "recruitment software",
                               "aday takip sistemi"],
        "people analytics": ["people analytics", "hr analytics", "workforce analytics",
                             "insan kaynakları analitiği"],
        "workforce planning": ["workforce planning", "iş gücü planlaması",
                               "headcount planning", "talent planning"],
    },
    # =====================================================================
    "Veri Görselleştirme 📊": {
        "tableau": ["tableau"],
        "power bi": ["power bi", "powerbi"],
        "looker": ["looker", "looker studio"],
        "metabase": ["metabase", "meta base"],
        "superset": ["superset", "apache superset"],
        "kibana": ["kibana"],
        "d3.js": ["d3.js", "d3js"],
        "plotly": ["plotly", "plot ly"],
        "matplotlib": ["matplotlib"],
        "seaborn": ["seaborn", "sea born"],
    },
}


# --- Düzleştirme: kategori ağacından tek-düzey SKILLS sözlüğü üret. ------------
# Aynı canonical iki kategoride görünürse SESSİZCE üzerine yazmak yerine HATA ver.
SKILLS: dict[str, list[str]] = {}
for _cat, _skills in SKILL_CATEGORIES.items():
    for _canon, _variants in _skills.items():
        if _canon in SKILLS:
            raise ValueError(f"skills.py: yinelenen canonical '{_canon}' (kategori: {_cat})")
        SKILLS[_canon] = _variants


def all_canonical() -> list[str]:
    """Tüm canonical beceri isimleri (rapor/dashboard için)."""
    return list(SKILLS.keys())


def category_of(canonical: str) -> str | None:
    """Bir canonical becerinin ait olduğu kategori etiketi (UI gruplaması için)."""
    for cat, skills in SKILL_CATEGORIES.items():
        if canonical in skills:
            return cat
    return None


def variant_count() -> int:
    return sum(len(v) for v in SKILLS.values())


if __name__ == "__main__":
    print(f"Kategori sayısı         : {len(SKILL_CATEGORIES)}")
    print(f"Canonical beceri sayısı : {len(SKILLS)}")
    print(f"Toplam varyant sayısı   : {variant_count()}")
    for cat, skills in SKILL_CATEGORIES.items():
        print(f"  {cat:32s} {len(skills):3d} beceri")
